# NumPy: Designed for Efficiency Across Large Datasets

In [4]:
import numpy as np 

In [2]:
my_list = list(range(1000000))
%timeit for _ in range(10): my_list2 = [2*x for x in my_list]

877 ms ± 45.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
my_arr = np.arange(1000000)
%timeit for _ in range(10): my_arr2 = my_arr * 2

15.1 ms ± 242 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


NumPy performs orders of maginitude better across large datasets

### ndarray: N-Dimensional Array

* Enables eficient computations in batch 
* All elements much be same type

In [10]:
data = np.random.randn(2,3)

In [11]:
data

array([[ 0.46843711, -0.23867673, -0.07654609],
       [ 1.94541469,  1.27081633,  0.0345795 ]])

In [12]:
data * 10

array([[ 4.68437108, -2.3867673 , -0.76546095],
       [19.45414693, 12.70816328,  0.34579495]])

In [13]:
data.shape

(2, 3)

In [14]:
data.ndim

2

In [15]:
data.size

6

#### Creating np arrays from python arrays: 

In [24]:
data1 = [1,2,3,4,5,6,7,8,9]; data2 = [[1,2,3,4], [5,6,7,8]]

In [26]:
type(data1), type(data2)

(list, list)

In [27]:
arr, arr2 = np.array(data1), np.array(data2)

In [28]:
arr, arr2

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [29]:
type(arr), type(arr2)

(numpy.ndarray, numpy.ndarray)

npArrays do not copy, they are views of the existing array