In [ ]:
import numpy as np


In [ ]:
#add codes to this cell to 
#1. load arrays from file "arrays.npz", which should be download to the same directory as this notebook 
#2. assign the first array from the file to arr_ids, the second one to arr_scores, and the third one to arr_names
#so that, 
#arr_names contain names of the students
#arr_ids contain ids of the tests that students took
#arr_scores contains scores that students earned on the corresponding tests.


In [ ]:
print ("arr_ids:\n",arr_ids)
print ("arr_scores:\n",arr_scores)
print ("arr_names:\n",arr_names)


'''
(20 points)
expected outputs from this cell are
arr_ids:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr_scores:
 [[78 87 72]
 [96 67 63]
 [68 89 87]
 [73 89 53]]
arr_names:
 [['Bob' 'Joe' 'Bob']
 ['Alex' 'Charles' 'Bob']
 ['Will' 'Bob' 'Alex']
 ['Bob' 'Will' 'John']]

'''

In [ ]:
#add codes to this cell to print out the highest scores that Bob earned among all the tests he took
#expected output is 89
#(10 points)

In [ ]:
#arr_scores contains scores in the range of [0,100]
#add codes to this cell to normlize the scores to the range of [0,1]

In [ ]:
print ("arr_scores :\n", arr_scores)


'''
(10 points)
Expected outputs are
arr_scores :
 [[0.78 0.87 0.72]
 [0.96 0.67 0.63]
 [0.68 0.89 0.87]
 [0.73 0.89 0.53]]
 '''

In [ ]:
# add codes to this cell 
#use slicing operations to change the scores of tests 3, 4, 6, 7 to 1.0

In [ ]:
print  ("arr_scores :\n", arr_scores)


'''
(10 points)
Expected outputs are
arr_scores :
 [[0.78 0.87 0.72]
 [1.   1.   0.63]
 [1.   1.   0.87]
 [0.73 0.89 0.53]]

'''

In [ ]:
'''
(50 points)
The following rules are used to assign GPA for each test based on the normalized scores

if normalized score >0.9, then GPA is 4.0
else if normalized score >0.7, then GPA is 3.0
else if normalized score >0.5, then GPA is 2.0
else if normalized score >0.3, then GPA is 1.0
else GPA is 0

Add codes to this cell to print out the average GPA for Bob.

'''

