In [1]:
import numpy as np

In [2]:
#add codes to this cell to 
#1. load arrays from file "arrays.npz", which should be download to the same directory as this notebook 
arrays = np.load("arrays.npz")
#2. assign the first array from the file to arr_ids, the second one to arr_scores, and the third one to arr_names
#so that, 
arr_ids = arrays['ids']
arr_scores = arrays['scores']
arr_names = arrays['names']
#arr_names contain names of the students
#arr_ids contain ids of the tests that students took
#arr_scores contains scores that students earned on the corresponding tests.

In [3]:
print ("arr_ids:\n",arr_ids)
print ("arr_scores:\n",arr_scores)
print ("arr_names:\n",arr_names)


'''
(20 points)
expected outputs from this cell are
arr_ids:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr_scores:
 [[78 87 72]
 [96 67 63]
 [68 89 87]
 [73 89 53]]
arr_names:
 [['Bob' 'Joe' 'Bob']
 ['Alex' 'Charles' 'Bob']
 ['Will' 'Bob' 'Alex']
 ['Bob' 'Will' 'John']]

'''

arr_ids:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr_scores:
 [[78 87 72]
 [96 67 63]
 [68 89 87]
 [73 89 53]]
arr_names:
 [['Bob' 'Joe' 'Bob']
 ['Alex' 'Charles' 'Bob']
 ['Will' 'Bob' 'Alex']
 ['Bob' 'Will' 'John']]


"\n(20 points)\nexpected outputs from this cell are\narr_ids:\n [[ 0  1  2]\n [ 3  4  5]\n [ 6  7  8]\n [ 9 10 11]]\narr_scores:\n [[78 87 72]\n [96 67 63]\n [68 89 87]\n [73 89 53]]\narr_names:\n [['Bob' 'Joe' 'Bob']\n ['Alex' 'Charles' 'Bob']\n ['Will' 'Bob' 'Alex']\n ['Bob' 'Will' 'John']]\n\n"

In [4]:
#add codes to this cell to print out the highest scores that Bob earned among all the tests he took
#expected output is 89
#(10 points)

#boolean indexing is incredibly useful
bob_indeces = arr_names == 'Bob'
bob_scores = arr_scores[bob_indeces]
max_bob_score = np.max(bob_scores)
max_bob_score

89

In [5]:
#arr_scores contains scores in the range of [0,100]
#add codes to this cell to normlize the scores to the range of [0,1]
arr_scores = arr_scores / 100


In [6]:
print ("arr_scores :\n", arr_scores)


'''
(10 points)
Expected outputs are
arr_scores :
 [[0.78 0.87 0.72]
 [0.96 0.67 0.63]
 [0.68 0.89 0.87]
 [0.73 0.89 0.53]]
 '''

arr_scores :
 [[0.78 0.87 0.72]
 [0.96 0.67 0.63]
 [0.68 0.89 0.87]
 [0.73 0.89 0.53]]


'\n(10 points)\nExpected outputs are\narr_scores :\n [[0.78 0.87 0.72]\n [0.96 0.67 0.63]\n [0.68 0.89 0.87]\n [0.73 0.89 0.53]]\n '

In [7]:
# add codes to this cell 
#use slicing operations to change the scores of tests 3, 4, 6, 7 to 1.0
arr_scores[1][0:2] = 1
arr_scores[2][0:2] = 1

In [8]:
print  ("arr_scores :\n", arr_scores)


'''
(10 points)
Expected outputs are
arr_scores :
 [[0.78 0.87 0.72]
 [1.   1.   0.63]
 [1.   1.   0.87]
 [0.73 0.89 0.53]]

'''

arr_scores :
 [[0.78 0.87 0.72]
 [1.   1.   0.63]
 [1.   1.   0.87]
 [0.73 0.89 0.53]]


'\n(10 points)\nExpected outputs are\narr_scores :\n [[0.78 0.87 0.72]\n [1.   1.   0.63]\n [1.   1.   0.87]\n [0.73 0.89 0.53]]\n\n'

In [15]:
'''
(50 points)
The following rules are used to assign GPA for each test based on the normalized scores

if normalized score >0.9, then GPA is 4.0
else if normalized score >0.7, then GPA is 3.0
else if normalized score >0.5, then GPA is 2.0
else if normalized score >0.3, then GPA is 1.0
else GPA is 0

Add codes to this cell to print out the average GPA for Bob.

'''
bob_gpa_points = 0
for score in bob_scores: 
    if score > 90: 
        bob_gpa_points += 4
    elif score > 70: 
        bob_gpa_points += 3
    elif score > 50: 
        bob_gpa_points += 2
    elif score > 30: 
        bob_gpa_points += 1
    else: 
        bob_gpa_points += 0
bob_gpa = bob_gpa_points / len(bob_scores)
print(bob_gpa)
    


2.8
